### ISSUE TITLE
error when running streamlit run simulate_agent.py

### ISSUE THREAD

**Issue by somashekarbrdtscblr** [NirDiamant/RAG-Harry-Potter#11]
using python 3.11
no error when installing requirements.txt
windows 10 
error at WEB/STREAMLIT :
![image](https://github.com/user-attachments/assets/107e3dad-ee01-482f-9f45-ae6de7f8b4c2)

error at CMD:
```
Controllable-RAG-Agent\functions_for_pipeline.py:3: LangChainDeprecationWarning: Importing FAISS from langchain.vectorstores is deprecated. Please replace deprecated imports:

>> from langchain.vectorstores import FAISS

with new imports of:

>> from langchain_community.vectorstores import FAISS
You can use the langchain cli to **automatically** upgrade many imports. Please see documentation here <https://python.langchain.com/v0.2/docs/versions/v0_2/>
  from langchain.vectorstores import  FAISS
D:\workspace\Controllable-RAG-Agent\functions_for_pipeline.py:4: LangChainDeprecationWarning: Importing OpenAIEmbeddings from langchain.embeddings is deprecated. Please replace deprecated imports:

>> from langchain.embeddings import OpenAIEmbeddings

with new imports of:

>> from langchain_community.embeddings import OpenAIEmbeddings
You can use the langchain cli to **automatically** upgrade many imports. Please see documentation here <https://python.langchain.com/v0.2/docs/versions/v0_2/>
  from langchain.embeddings import OpenAIEmbeddings
D:\workspace\Controllable-RAG-Agent\simulate_agent.py:5: LangChainDeprecationWarning: As of langchain-core 0.3.0, LangChain uses pydantic v2 internally. The langchain_core.pydantic_v1 module was a compatibility shim for pydantic v1, and should no longer be used. Please update the code to import from Pydantic directly.

For example, replace imports like: `from langchain_core.pydantic_v1 import BaseModel`
with: `from pydantic import BaseModel`
or the v1 compatibility namespace if you are working in a code base that has not been fully upgraded to pydantic 2 yet.         from pydantic.v1 import BaseModel

  from functions_for_pipeline import *
D:\workspace\Controllable-RAG-Agent\functions_for_pipeline.py:35: LangChainDeprecationWarning: The class `OpenAIEmbeddings` was deprecated in LangChain 0.0.9 and will be removed in 1.0. An updated version of the class exists in the langchain-openai package and should be used instead. To use it run `pip install -U langchain-openai` and import as `from langchain_openai import OpenAIEmbeddings`.
  embeddings = OpenAIEmbeddings()
2024-09-16 13:03:57.113 Uncaught app exception
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
  File "D:\workspace\Controllable-RAG-Agent\simulate_agent.py", line 5, in <module>
    from functions_for_pipeline import *
  File "D:\workspace\Controllable-RAG-Agent\functions_for_pipeline.py", line 47, in <module>
    chunks_query_retriever, chapter_summaries_query_retriever, book_quotes_query_retriever = create_retrievers()
                                                                                             ^^^^^^^^^^^^^^^^^^^
  File "D:\workspace\Controllable-RAG-Agent\functions_for_pipeline.py", line 36, in create_retrievers
    chunks_vector_store =  FAISS.load_local("chunks_vector_store", embeddings, allow_dangerous_deserialization=True)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\langchain_community\vectorstores\faiss.py", line 1203, in load_local
    index = faiss.read_index(str(path / f"{index_name}.faiss"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\faiss\swigfaiss_avx2.py", line 10409, in read_index
    return _swigfaiss_avx2.read_index(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error in __cdecl faiss::FileIOReader::FileIOReader(const char *) at D:\a\faiss-wheels\faiss-wheels\faiss\faiss\impl\io.cpp:68: Error: 'f' failed: could not open chunks_vector_store\index.faiss for reading: No such file or directory

```

**Comment by NirDiamant** [comment]
Thanks for the heads-up!
Please try now

**Comment by somashekarbrdtscblr** [comment]
after pulling latest code
but the import is right and function exists
now having this error : 

![image](https://github.com/user-attachments/assets/cf1535a2-7cba-4cf8-a99d-e60a3eb637e9)


after updating
``` from functions_for_pipeline import create_agent ```

want to use OPENAI models
created .env file in same directory
added 
``` OPENAI_API_KEY=sk-proj-OPENAIKEY ```
where do i specify it to use open ai model

another error is occuring
![image](https://github.com/user-attachments/assets/e1bf4ada-4727-4dce-bd63-25aaf2897388)

error : 

```


  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://192.168.0.124:8501

D:\workspace\Controllable-RAG-Agent\functions_for_pipeline.py:3: LangChainDeprecationWarning: Importing FAISS from langchain.vectorstores is deprecated. Please replace deprecated imports:

>> from langchain.vectorstores import FAISS

with new imports of:

>> from langchain_community.vectorstores import FAISS
You can use the langchain cli to **automatically** upgrade many imports. Please see documentation here <https://python.langchain.com/v0.2/docs/versions/v0_2/>
  from langchain.vectorstores import  FAISS
D:\workspace\Controllable-RAG-Agent\functions_for_pipeline.py:4: LangChainDeprecationWarning: Importing OpenAIEmbeddings from langchain.embeddings is deprecated. Please replace deprecated imports:

>> from langchain.embeddings import OpenAIEmbeddings

with new imports of:

>> from langchain_community.embeddings import OpenAIEmbeddings
You can use the langchain cli to **automatically** upgrade many imports. Please see documentation here <https://python.langchain.com/v0.2/docs/versions/v0_2/>
  from langchain.embeddings import OpenAIEmbeddings
D:\workspace\Controllable-RAG-Agent\simulate_agent.py:5: LangChainDeprecationWarning: As of langchain-core 0.3.0, LangChain uses pydantic v2 internally. The langchain_core.pydantic_v1 module was a compatibility shim for pydantic v1, and should no longer be used. Please update the code to import from Pydantic directly.

For example, replace imports like: `from langchain_core.pydantic_v1 import BaseModel`
with: `from pydantic import BaseModel`
or the v1 compatibility namespace if you are working in a code base that has not been fully upgraded to pydantic 2 yet.         from pydantic.v1 import BaseModel

  from functions_for_pipeline import *
D:\workspace\Controllable-RAG-Agent\functions_for_pipeline.py:35: LangChainDeprecationWarning: The class `OpenAIEmbeddings` was deprecated in LangChain 0.0.9 and will be removed in 1.0. An updated version of the class exists in the langchain-openai package and should be used instead. To use it run `pip install -U langchain-openai` and import as `from langchain_openai import OpenAIEmbeddings`.
  embeddings = OpenAIEmbeddings()
2024-09-16 14:58:48.544 Uncaught app exception
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
  File "D:\workspace\Controllable-RAG-Agent\simulate_agent.py", line 5, in <module>
    from functions_for_pipeline import *
  File "D:\workspace\Controllable-RAG-Agent\functions_for_pipeline.py", line 252, in <module>
    is_relevant_content_chain = create_is_relevant_content_chain()
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\workspace\Controllable-RAG-Agent\functions_for_pipeline.py", line 247, in create_is_relevant_content_chain
    partial_variables={"format_instructions": is_relevant_json_parser.get_format_instructions()},
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\langchain_core\output_parsers\json.py", line 112, in get_format_instructions
    schema = {k: v for k, v in self._get_schema(self.pydantic_object).items()}
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\langchain_core\output_parsers\json.py", line 57, in _get_schema
    return pydantic_object.model_json_schema()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'Relevance' has no attribute 'model_json_schema'
2024-09-16 14:58:48.650 Uncaught app exception
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
  File "D:\workspace\Controllable-RAG-Agent\simulate_agent.py", line 238, in <module>
    main()
  File "D:\workspace\Controllable-RAG-Agent\simulate_agent.py", line 203, in main
    plan_and_execute_app =create_agent()
                          ^^^^^^^^^^^^
NameError: name 'create_agent' is not defined

```

**Comment by NirDiamant** [comment]
Please try again now

**Comment by somashekarbrdtscblr** [comment]
i tried replacing all 4 ChatGroq function call with ChatOpenAI

**Comment by somashekarbrdtscblr** [comment]
> Please try again now

ok let me try

**Comment by somashekarbrdtscblr** [comment]
hey there
awesome that your responding early

here some new error i am facing
i have been trying to set this up past 2 days

at streamlit

![image](https://github.com/user-attachments/assets/b317844c-2411-4ec6-9325-b0b4d5354f41)


at CMD:

```

 You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://192.168.0.124:8501

D:\workspace\Controllable-RAG-Agent\functions_for_pipeline.py:3: LangChainDeprecationWarning: Importing FAISS from langchain.vectorstores is deprecated. Please replace deprecated imports:

>> from langchain.vectorstores import FAISS

with new imports of:

>> from langchain_community.vectorstores import FAISS
You can use the langchain cli to **automatically** upgrade many imports. Please see documentation here <https://python.langchain.com/v0.2/docs/versions/v0_2/>
  from langchain.vectorstores import  FAISS
D:\workspace\Controllable-RAG-Agent\functions_for_pipeline.py:4: LangChainDeprecationWarning: Importing OpenAIEmbeddings from langchain.embeddings is deprecated. Please replace deprecated imports:

>> from langchain.embeddings import OpenAIEmbeddings

with new imports of:

>> from langchain_community.embeddings import OpenAIEmbeddings
You can use the langchain cli to **automatically** upgrade many imports. Please see documentation here <https://python.langchain.com/v0.2/docs/versions/v0_2/>
  from langchain.embeddings import OpenAIEmbeddings
D:\workspace\Controllable-RAG-Agent\simulate_agent.py:5: LangChainDeprecationWarning: As of langchain-core 0.3.0, LangChain uses pydantic v2 internally. The langchain_core.pydantic_v1 module was a compatibility shim for pydantic v1, and should no longer be used. Please update the code to import from Pydantic directly.

For example, replace imports like: `from langchain_core.pydantic_v1 import BaseModel`
with: `from pydantic import BaseModel`
or the v1 compatibility namespace if you are working in a code base that has not been fully upgraded to pydantic 2 yet.         from pydantic.v1 import BaseModel

  from functions_for_pipeline import *
D:\workspace\Controllable-RAG-Agent\functions_for_pipeline.py:35: LangChainDeprecationWarning: The class `OpenAIEmbeddings` was deprecated in LangChain 0.0.9 and will be removed in 1.0. An updated version of the class exists in the langchain-openai package and should be used instead. To use it run `pip install -U langchain-openai` and import as `from langchain_openai import OpenAIEmbeddings`.
  embeddings = OpenAIEmbeddings()
2024-09-16 15:12:47.857 Uncaught app exception
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\streamlit\runtime\scriptrunner\exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "C:\Python311\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 590, in code_to_exec
    exec(code, module.__dict__)
  File "D:\workspace\Controllable-RAG-Agent\simulate_agent.py", line 5, in <module>
    from functions_for_pipeline import *
  File "D:\workspace\Controllable-RAG-Agent\functions_for_pipeline.py", line 252, in <module>
    is_relevant_content_chain = create_is_relevant_content_chain()
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\workspace\Controllable-RAG-Agent\functions_for_pipeline.py", line 247, in create_is_relevant_content_chain
    partial_variables={"format_instructions": is_relevant_json_parser.get_format_instructions()},
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\langchain_core\output_parsers\json.py", line 112, in get_format_instructions
    schema = {k: v for k, v in self._get_schema(self.pydantic_object).items()}
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\langchain_core\output_parsers\json.py", line 57, in _get_schema
    return pydantic_object.model_json_schema()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'Relevance' has no attribute 'model_json_schema'

````

**Comment by somashekarbrdtscblr** [comment]
is it possible to make this a docker container and run it with ease 
there might be problems with version mismatch

**Comment by NirDiamant** [comment]
I think it was a matter of output formatting. changed the code accordingly, please try again now :)

**Comment by somashekarbrdtscblr** [comment]
great it runs now 

also can is there a option to add my knowledge data for vector store?

error when i run the agent :

![image](https://github.com/user-attachments/assets/d9e8a409-d8c9-4e7e-98ca-345d4a21366d)

CMD logs:
```  
Anonymizing question
'--------------------'

```

**Comment by NirDiamant** [comment]
Please try now, I fixed it. also please notice that the requirements file is updated

**Comment by somashekarbrdtscblr** [comment]
> Please try now, I fixed it. also please notice that the requirements file is updated

there still some error  persists

if we could implement docker for this  there would be no error

cmd: `pip install -r requirements.txt`

error: 
![image](https://github.com/user-attachments/assets/2870e3de-a73b-4be3-90ce-43bebfc34945)


cmd : `streamlit run simulate_agent.py`


![image](https://github.com/user-attachments/assets/62e307ec-609d-4aa1-98ab-b76a34e355e1)

**Comment by NirDiamant** [comment]
You can add a docker implementation and open a PR :)

**Comment by nadavox** [comment]
@NirDiamant after the PR, we can close this issue too no ?

**Comment by somashekarbrdtscblr** [comment]
ERROR: 
![image](https://github.com/user-attachments/assets/b2443d2a-2879-40c8-b987-b77c3a1cde2b)


cmd : docker-compose up --build 

have you even tried docker yourself ?

**Comment by nadavox** [comment]
@somashekarbrdtscblr can you tell me the commands you wrote in the terminal until you get the error, start from git clone ? the docker worked for me with no problem .
remember to do these steps before run the docker-compose command:
Installation
Clone the repository:
git clone https://github.com/NirDiamant/Controllable-RAG-Agent.git
cd Controllable-RAG-Agent
Set up environment variables: Create a .env file in the root directory with your API key:
OPENAI_API_KEY=
GROQ_API_KEY=
you can look at the .env.example file for reference.

**Comment by somashekarbrdtscblr** [comment]
> @somashekarbrdtscblr can you tell me the commands you wrote in the terminal until you get the error, start from git clone ? the docker worked for me with no problem . remember to do these steps before run the docker-compose command: Installation Clone the repository: git clone https://github.com/NirDiamant/Controllable-RAG-Agent.git cd Controllable-RAG-Agent Set up environment variables: Create a .env file in the root directory with your API key: OPENAI_API_KEY= GROQ_API_KEY= you can look at the .env.example file for reference.



`git clone https://github.com/NirDiamant/Controllable-RAG-Agent.git`

`cd Controllable-RAG-Agent`

add .env file containing OPENAI_API_KEY=
GROQ_API_KEY=

`docker-compose up --build`

**Comment by nadavox** [comment]
you right. something off. I need to look into it. Thank you.

**Comment by somashekarbrdtscblr** [comment]
> you right. something off. I need to look into it. Thank you.

some dependencies are missing here
test your docker file

**Comment by nadavox** [comment]
yes you right. 
apperntaly I need to instal rust (needed by some Python packages so I added a line that install rust) 
if you want it to work for now until MR change the docker file to this:
```
FROM python:3.11-slim-buster

# Set the working directory in the container
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    g++ \
    curl \
    git \
    && rm -rf /var/lib/apt/lists/*

# Install Rust (required by some Python packages)
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y

# Ensure Rust and Cargo are available in the path
ENV PATH="/root/.cargo/bin:${PATH}"

# Upgrade pip and install wheel
RUN pip install --no-cache-dir --upgrade pip wheel setuptools

# Copy the requirements file into the container at /app
COPY requirements.txt ./

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the current directory contents into the container at /app
COPY . .

# Command to run the application
CMD ["streamlit", "run", "simulate_agent.py"]
```

**Comment by NirDiamant** [comment]
@nadavox can we close this issue?

**Comment by nadavox** [comment]
Yes
